package cl.vozlocal.app;

import android.app.*;
import android.content.*;
import android.net.Uri;
import android.os.*;
import android.view.*;
import android.widget.*;
import android.text.InputType;
import java.util.concurrent.*;

public class SettingsActivity extends Screen {
    private Settings settings;private TextView keyStatus,folderStatus;private Button keyButton;
    private final ExecutorService io=Executors.newSingleThreadExecutor();private HttpApi http;
    @Override public void onCreate(Bundle state){super.onCreate(state);settings=new Settings(this);render();}
    private void render(){
        setup("Ajustes","Todo se guarda en tu teléfono. El audio solo sale al transcribir con el proveedor que elijas.");
        LinearLayout appearance=card("Apariencia");
        String mode=AppTheme.appearance(this);choice(appearance,"Tema",new String[]{"Usar el del teléfono","Claro","Oscuro"},mode.equals("dark")?2:mode.equals("light")?1:0,index->{settings.prefs.edit().putString("appearance",new String[]{"system","light","dark"}[index]).apply();recreate();});
        help(appearance,"El tema se aplica también a la biblioteca, las transcripciones y los controles de importación.");
        LinearLayout api=card("Proveedor y modelo");
        choice(api,"Proveedor",new String[]{"OpenAI","API compatible personalizada"},settings.provider().equals("openai")?0:1,index->{settings.prefs.edit().putString("provider",index==0?"openai":"custom").apply();Pipeline.schedule(this,true);render();});
        if(settings.provider().equals("openai")){
            String[] models={"gpt-4o-transcribe-diarize","gpt-4o-transcribe","gpt-4o-mini-transcribe","whisper-1"};int selected=java.util.Arrays.asList(models).indexOf(settings.prefs.getString("openaiModel",models[0]));
            choice(api,"Modelo",new String[]{"Separar voces · GPT-4o Diarize","Texto · GPT-4o Transcribe","Texto · GPT-4o Mini","Texto · Whisper"},Math.max(0,selected),index->{settings.prefs.edit().putString("openaiModel",models[index]).apply();Pipeline.schedule(this,true);});
            help(api,"Solo Diarize separa hablantes en esta integración. Cambiar el modelo afecta a los próximos trabajos; las transcripciones guardadas se conservan.");
        }else{
            help(api,"Requiere /audio/transcriptions compatible con OpenAI. Una API de chat por sí sola no sirve para transcribir. Cada proveedor puede admitir formatos y funciones diferentes.");
            Button endpoint=button("Configurar servidor y modelo",false);endpoint.setOnClickListener(v->custom());api.addView(endpoint);
        }
        keyStatus=text("",14,GREEN);api.addView(keyStatus);
        keyButton=button("",false);keyButton.setOnClickListener(v->keyDialog());api.addView(keyButton);
        Button verify=button("Comprobar conexión",true);verify.setOnClickListener(v->{if(!settings.hasKey()){message("Falta la clave","Configura una clave para este proveedor.");return;}background(verify,()->{new OpenAiClient(http).verify(settings.config());return "El servidor respondió y reconoce el modelo. Esto no prueba todavía la carga de audio, el saldo ni la separación de voces. Algunos servidores compatibles no publican /models y requieren probar con un audio.";});});api.addView(verify);
        Button remove=button("Eliminar clave",false);remove.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("¿Eliminar la clave de este proveedor?").setNegativeButton("Cancelar",null).setPositiveButton("Eliminar",(d,w)->{try{settings.saveKey("");getSystemService(android.app.job.JobScheduler.class).cancel(Pipeline.JOB_ID);refresh();}catch(Exception e){message("Clave","No se pudo eliminar.");}}).show());api.addView(remove);
        choice(api,"Idioma",new String[]{"Español","Detección automática"},settings.language().equals("es")?0:1,index->settings.prefs.edit().putString("language",index==0?"es":"").apply());
        LinearLayout timing=card("Cuándo transcribir");toggle(timing,"Transcribir al guardar o importar","automatic",settings.automatic());
        choice(timing,"Conexión permitida",new String[]{"Solo Wi-Fi / red no medida","También datos móviles"},settings.wifiOnly()?0:1,index->{settings.prefs.edit().putBoolean("wifi",index==0).apply();Pipeline.schedule(this,true);});
        toggle(timing,"Solo mientras está cargando","charging",settings.charging());
        help(timing,"También se aplica al envío manual. Con batería baja el trabajo espera. Android puede retrasar las tareas en segundo plano. El uso de la API se cobra en tu cuenta.");
        LinearLayout storage=card("Carpeta del teléfono");folderStatus=text("",14,MUTED);storage.addView(folderStatus);
        Button folder=button("Elegir o crear carpeta",false);folder.setOnClickListener(v->{Intent pick=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(pick,51);});storage.addView(folder);
        Button copy=button("Actualizar copias de la biblioteca",false);copy.setOnClickListener(v->{for(Recording r:Recording.list(this))LocalStorage.enqueue(this,r.id);message("Copia local","Se actualizará la carpeta elegida. Puedes ver el resultado de cada copia en la biblioteca.");});storage.addView(copy);
        Button unlink=button("Dejar de copiar a esa carpeta",false);unlink.setOnClickListener(v->{String old=settings.prefs.getString("localTree","");settings.prefs.edit().remove("localTree").apply();if(!old.isEmpty())try{getContentResolver().releasePersistableUriPermission(Uri.parse(old),Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);}catch(Exception ignored){}refresh();});storage.addView(unlink);
        help(storage,"Elige una carpeta del almacenamiento del dispositivo. Android permite crearla y ponerle nombre. Cada grabación tendrá una subcarpeta con audio, título y transcripción. La app conserva su propia copia: se pierde al desinstalar, pero la carpeta elegida se conserva. Borrar una grabación no borra estas copias.");
        LinearLayout recording=card("Grabación");toggle(recording,"Preguntar un título antes de grabar","askTitle",settings.askTitle());
        LinearLayout practice=card("Pruebas y ayuda");help(practice,"Explora una transcripción de ejemplo y cambia los nombres de sus hablantes. No usa tu clave ni consume API.");
        Button demo=button("Probar edición de hablantes",false);demo.setOnClickListener(v->startActivity(new Intent(this,TranscriptActivity.class).putExtra("demo",true)));practice.addView(demo);
        LinearLayout dev=card("Diagnóstico y soporte");help(dev,"Registro técnico local: botones, pantallas, etapas, tiempos, códigos de error y reintentos. Máximo aproximado 4 MB; el informe incluye los últimos 30 días disponibles. No contiene claves, títulos, audio ni texto transcrito. No se envía automáticamente.");
        Button report=button("Compartir informe de soporte",false);report.setOnClickListener(v->{report.setEnabled(false);io.execute(()->{try{Diagnostics.export(this);runOnUiThread(()->{report.setEnabled(true);shareFile("support.txt","Informe de soporte");});}catch(Exception e){runOnUiThread(()->{report.setEnabled(true);message("Informe","No se pudo generar el informe.");});}});});dev.addView(report);
        Button clear=button("Borrar registros de diagnóstico",false);clear.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("¿Borrar los registros locales?").setNegativeButton("Cancelar",null).setPositiveButton("Borrar",(d,w)->{Diagnostics.clear(this);message("Registros borrados","Las grabaciones se conservan.");}).show());dev.addView(clear);

        help(page,"Voz local 0.4.0 · Software libre · Licencia MIT");refresh();
    }
    private void refresh(){keyStatus.setText(settings.hasKey()?"Clave configurada · cifrada en este teléfono":"Sin clave para este proveedor");keyButton.setText(settings.hasKey()?"Cambiar clave":"Ingresar clave de API");String tree=settings.prefs.getString("localTree","");folderStatus.setText(tree.isEmpty()?"Solo almacenamiento privado de la app":"Carpeta: "+android.provider.DocumentsContract.getTreeDocumentId(Uri.parse(tree)));}
    private void keyDialog(){LinearLayout box=column();box.setPadding(dp(24),dp(8),dp(24),dp(8));EditText input=input(box,"Clave de API","Pega tu clave");input.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);input.setSaveEnabled(false);input.setImportantForAutofill(View.IMPORTANT_FOR_AUTOFILL_NO);help(box,"La clave se guarda cifrada. Nunca aparecerá en los informes.");AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Configurar clave").setView(box).setNegativeButton("Cancelar",null).setPositiveButton("Guardar",null).create();dialog.setOnShowListener(d->dialog.getButton(-1).setOnClickListener(v->{try{if(input.length()==0){input.setError("Ingresa una clave");return;}settings.saveKey(input.getText().toString());input.setText("");refresh();dialog.dismiss();}catch(Exception e){input.setError("No se pudo guardar. Comprueba que no haya espacios.");}}));dialog.show();dialog.getWindow().addFlags(WindowManager.LayoutParams.FLAG_SECURE);}
    private void custom(){LinearLayout box=column();box.setPadding(dp(24),0,dp(24),0);EditText base=input(box,"URL base HTTPS","https://proveedor.com/v1");base.setText(settings.prefs.getString("customBase",""));EditText model=input(box,"Identificador del modelo","modelo-de-transcripcion");model.setText(settings.prefs.getString("customModel",""));CheckBox voices=new CheckBox(this);voices.setText("Admite diarized_json y chunking_strategy");voices.setChecked(settings.prefs.getBoolean("customSpeakers",false));box.addView(voices);help(box,"Enviarás audio y tu clave al servidor indicado. Al cambiar de servidor se elimina su clave anterior para que ingreses la correspondiente.");AlertDialog dialog=new AlertDialog.Builder(this).setTitle("API compatible").setView(box).setNegativeButton("Cancelar",null).setPositiveButton("Guardar",null).create();dialog.setOnShowListener(d->dialog.getButton(-1).setOnClickListener(v->{try{ProviderConfig config=new ProviderConfig("custom",base.getText().toString().trim(),model.getText().toString().trim(),"",voices.isChecked());if(!config.base.equals(settings.prefs.getString("customBase","")))settings.saveKey("");settings.prefs.edit().putString("customBase",config.base).putString("customModel",config.model).putBoolean("customSpeakers",config.speakers).apply();Pipeline.schedule(this,true);dialog.dismiss();refresh();}catch(Exception e){base.setError("Usa una URL HTTPS sin credenciales ni parámetros y un modelo válido.");}}));dialog.show();}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==51&&result==RESULT_OK&&data!=null&&data.getData()!=null){try{Uri tree=data.getData();if((data.getFlags()&Intent.FLAG_GRANT_WRITE_URI_PERMISSION)==0)throw new SecurityException();getContentResolver().takePersistableUriPermission(tree,Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);settings.prefs.edit().putString("localTree",tree.toString()).apply();refresh();for(Recording r:Recording.list(this))LocalStorage.enqueue(this,r.id);}catch(Exception e){message("Carpeta","No se obtuvo permiso de escritura. Elige otra carpeta.");}}}
    private void toggle(LinearLayout p,String label,String key,boolean initial){Switch s=new Switch(this);s.setText(label);s.setTextColor(INK);s.setTextSize(16);s.setMinHeight(dp(64));s.setChecked(initial);s.setOnCheckedChangeListener((b,on)->{settings.prefs.edit().putBoolean(key,on).apply();if(key.equals("automatic")&&on&&Build.VERSION.SDK_INT>=33&&checkSelfPermission(android.Manifest.permission.POST_NOTIFICATIONS)!=android.content.pm.PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{android.Manifest.permission.POST_NOTIFICATIONS},101);Diagnostics.event("setting_changed",null,"action",key,"result",on);Pipeline.schedule(this,true);});p.addView(s);}
    interface Choice{void select(int index);}
    private void choice(LinearLayout p,String label,String[] options,int selected,Choice choice){label(p,label);Spinner spinner=new Spinner(this);spinner.setContentDescription(label);spinner.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,options));spinner.setSelection(selected);p.addView(spinner,new LinearLayout.LayoutParams(-1,dp(56)));spinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){int previous=selected;public void onNothingSelected(AdapterView<?> a){}public void onItemSelected(AdapterView<?> a,View v,int index,long id){if(index!=previous){previous=index;Diagnostics.event("setting_changed",null,"action",label,"result",index);choice.select(index);}}});}
    interface Task{String run()throws Exception;}
    private void background(Button button,Task task){button.setEnabled(false);http=new HttpApi();io.execute(()->{String result;try{result=task.run();}catch(Exception e){result=e instanceof HttpApi.UserAction?e.getMessage():"No se pudo conectar. Revisa la URL y tu conexión.";}String value=result;runOnUiThread(()->{if(!isDestroyed()){button.setEnabled(true);message("Conexión",value);}});});}
    @Override protected void onDestroy(){if(http!=null)http.cancel();io.shutdown();super.onDestroy();}
}
